name: Test Workflow

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create and Activate Virtual Environment
        run: |
          python -m venv ${{ github.workspace }}/.venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Verify Installed Packages
        run: |
          source .venv/bin/activate
          pip list
        shell: bash

      # Debugging Steps
      - name: Debug Current Directory
        run: pwd

      - name: List Files
        run: ls -la ${{ github.workspace }}

      - name: Upload Virtual Environment
        uses: actions/upload-artifact@v4
        with:
          name: python-env
          path: ${{ github.workspace }}/.venv

  reuse:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Download Virtual Environment
        uses: actions/download-artifact@v4
        with:
          name: python-env

      - name: Activate Virtual Environment and Verify Packages
        run: |
          source .venv/bin/activate
          pip list
        shell: bash